#monpremiercode

In [1]:
equipe = "Real Madrid"
type_sport = "football"
nombre_joueurs = 11
numero_joueur_5 = "Bellingham"

print("Nom de l'équipe :", equipe)
print("Nom du joueur portant le numéro 5 :", numero_joueur_5)

Nom de l'équipe : Real Madrid
Nom du joueur portant le numéro 5 : Bellingham

In [3]:
import pandas

ModuleNotFoundError: No module named 'pandas'

In [5]:
import pandas as pd

In [26]:
data=pd.read_csv(r"C:\Users\Gammoudi\Downloads\dataset.csv")

In [27]:
data.head(10)

,FacilityID,URL,Name,FacilityType,Address1,Town,State,AddressNote,Latitude,Longitude,...,Ambulant,Accessible,LHTransfer,RHTransfer,ToiletNote,SharpsDisposal,DrinkingWater,SanitaryDisposal,MensPadDisposal,Shower
0,1,https://toiletmap.gov.au/facility/1,Sandy Beach Reserve,Park or reserve,"Lost 15525, West Road",Bassendean,WA,NaN,-31.921836,115.950206,...,False,True,False,False,NaN,True,True,True,False,False
1,2,https://toiletmap.gov.au/facility/2,Point Reserve,Park or reserve,"Lot 197, North Road",Bassendean,WA,NaN,-31.904410,115.960991,...,False,True,False,False,NaN,True,True,True,False,False
2,3,https://toiletmap.gov.au/facility/3,Success Hill Reserve,Park or reserve,"Lot 2838, Seventh Avenue",Bassendean,WA,NaN,-31.896289,115.955781,...,False,True,False,False,NaN,True,True,True,False,True
3,4,https://toiletmap.gov.au/facility/4,Jubilee Reserve,Park or reserve,"Lot 6322, Robinson Road",Eden Hill,WA,NaN,-31.891474,115.940164,...,False,False,False,False,NaN,True,False,True,False,False
4,5,https://toiletmap.gov.au/facility/5,Ashfield Reserve,Park or reserve,"Lot 12061, 2 Coulston Road",Ashfield,WA,NaN,-31.913433,115.936477,...,False,True,False,False,NaN,True,True,True,False,False
5,6,https://toiletmap.gov.au/facility/6,BIC Townsite - James Street,Park or reserve,10 Whitfields Street,Bassendean,WA,This toilet block has been damaged by fire and...,-31.903978,115.950071,...,False,True,False,False,Public toilets closed due to fire damage.,False,False,False,False,False
6,7,https://toiletmap.gov.au/facility/7,Mary Crescent Reserve,Park or reserve,Mary Crescent,Eden Hill,WA,NaN,-31.890366,115.948090,...,False,True,False,False,NaN,True,True,True,False,False
7,9,https://toiletmap.gov.au/facility/9,Bassendean Oval West,Sporting facility,"Lot 246, Old Perth Road",Bassendean,WA,NaN,-31.903716,115.956490,...,False,False,False,False,NaN,False,False,False,False,False
8,15,https://toiletmap.gov.au/facility/15,Apex Park,Park or reserve,Moranbah Access Road,Moranbah,QLD,NaN,-22.014444,148.045242,...,False,False,False,False,NaN,False,False,False,False,False
9,16,https://toiletmap.gov.au/facility/16,Lions Park,Park or reserve,12 Belyando Avenue,Moranbah,QLD,NaN,-21.999341,148.043973,...,False,False,False,False,NaN,False,False,False,False,False